# Generated by Django 5.0.2 on 2024-11-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent',
            field=models.CharField(choices=[('sent', 'Sent'), ('not sent', 'Not Sent')], default='not sent', max_length=10),
        ),
    ]
