# Generated by Django 5.0.2 on 2024-11-10 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_invoice_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvoiceSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_seed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.invoiceseed'),
        ),
    ]
