# Generated by Django 5.0.2 on 2024-11-10 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_invoice_seed_invoiceitem_invoice_seed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_seed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='invoice_seed',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice_seed',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='is_draft',
            new_name='save_as_draft',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_with_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='InvoiceSeed',
        ),
    ]
