# Generated by Django 5.0.2 on 2024-11-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_invoice_invoice_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='share_link_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
