# Generated by Django 5.0.2 on 2024-11-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_invoice_share_link_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_amount_with_vat',
            new_name='total_amount_final',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_rate_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
