# Generated by Django 5.0.2 on 2024-11-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_total_amount_with_vat_invoice_total_amount_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
