# Generated by Django 5.0.2 on 2024-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_invoiceitem_title_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
