# Generated by Django 5.0.2 on 2024-11-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_invoiceitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_invoice_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
